In [2]:
pip install torch

     |████████████████████████████████| 119.6 MB 10.3 MB/s eta 0:00:01  |▋                               | 2.3 MB 893 kB/s eta 0:02:12     |███████████████████████████████▉| 118.7 MB 10.3 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [3]:
import torch
import numpy as np

# numpy to torch

In [4]:
np_data=np.arange(6).reshape((2,3))
torch_data=torch.from_numpy(np_data)

In [9]:
print(np_data)
print(type(np_data))

[[0 1 2]
 [3 4 5]]
<class 'numpy.ndarray'>


In [10]:
print(torch_data)
print(type(torch_data))

tensor([[0, 1, 2],
        [3, 4, 5]])
<class 'torch.Tensor'>


# torch to numpy

In [12]:
tensor2array=torch_data.numpy()

In [13]:
print(tensor2array)

[[0 1 2]
 [3 4 5]]


# 運算符號

In [14]:
data=[-1,-2,2,2]
tensor=torch.FloatTensor(data)    #32bit
print(tensor)

tensor([-1., -2.,  2.,  2.])


In [24]:
print(
'np:',np.abs(data),
'\ntensor:',torch.abs(tensor)
)

np: [1 2 2 2] 
tensor: tensor([1., 2., 2., 2.])


In [25]:
print(
'np:',np.sin(data),
'\ntensor:',torch.sin(tensor)
)

np: [-0.84147098 -0.90929743  0.90929743  0.90929743] 
tensor: tensor([-0.8415, -0.9093,  0.9093,  0.9093])


In [26]:
print(
'np:',np.mean(data),
'\ntensor:',torch.mean(tensor)
)

np: 0.25 
tensor: tensor(0.2500)


# 矩陣運算

In [32]:
data=[[1,2],[3,4]]
tensor=torch.FloatTensor(data)
data=np.array(data)

In [36]:
print(
'np:',np.matmul(data,data),#matricsmultiply
'\nnp:',data.dot(data),
'\ntensor:',torch.mm(tensor,tensor),#mm
#'\ntensor:',tensor.dot(tensor)不能用了，原本會自動展開成為1平方加到4平方
)

np: [[ 7 10]
 [15 22]] 
np: [[ 7 10]
 [15 22]] 
tensor: tensor([[ 7., 10.],
        [15., 22.]])
