In [1]:
from torch.autograd import Variable
import torch

In [2]:
tensor=torch.FloatTensor([[1,2],[3,4]])
variable=Variable(tensor,requires_grad=True)#一般為false

In [3]:
variable

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [4]:
tensor1=torch.FloatTensor([[2,2],[3,4]])
c=Variable(tensor1,requires_grad=True)

In [5]:
t_out=torch.mean(tensor*tensor)#tensor平方
v_out=torch.mean(variable*variable)
g_out=torch.mean(variable*c)
print('t_out:',t_out)#tensor不能反向傳播
print('v_out:',v_out)
print('g_out:',g_out)

t_out: tensor(7.5000)
v_out: tensor(7.5000, grad_fn=<MeanBackward0>)
g_out: tensor(7.7500, grad_fn=<MeanBackward0>)


In [6]:
#v_out=1/4*sum(var*var)
#d(v_out)/d(var)=variable/2
v_out.backward()
print(variable.grad)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [7]:
g_out.backward()
print(variable.grad)

tensor([[1.0000, 1.5000],
        [2.2500, 3.0000]])


In [8]:
print(variable.data)#變tensor

tensor([[1., 2.],
        [3., 4.]])


# 想將variable轉成numpy和將tensor轉成numpy不同

In [9]:
#variable.numpy()錯的
variable.data.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [16]:
tensor2=torch.FloatTensor([[3,2],[3,4]])
variable2=Variable(tensor2,requires_grad=True)#一般為false

In [17]:
tensor3=torch.FloatTensor([[3,2],[3,4]])
variable3=Variable(tensor3,requires_grad=True)#一般為false